services:
  frankenphp:
    build:
      context: .
    user: "1000:1000"
    working_dir: /app
    command: frankenphp php-server --listen :8000 --root public/
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: local
      APP_DEBUG: true
      WATCH_FILES: 1

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dishy_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: marley
      MYSQL_PASSWORD: secret
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - frankenphp

volumes:
  mysql_data:
